# Basics of NumPy Arrays

In [ ]:
import numpy as np


Learn how to create NumPy arrays and inspect their attributes.

Creating Arrays

In [ ]:
# Create a 1D array from a list
arr_1d = np.array([1, 2, 3, 4, 5])
print("1D Array:", arr_1d)

# Create a 2D array from a nested list
arr_2d = np.array([[1, 2, 3], [4, 5, 6]])
print("\n2D Array:\n", arr_2d)


1D Array: [1 2 3 4 5]

2D Array:
 [[1 2 3]
 [4 5 6]]


Inspecting Array Attributes

In [ ]:
# Print the shape, size, and data type of arr_2d
print("Shape:", arr_2d.shape)
print("Size:", arr_2d.size)
print("Data Type:", arr_2d.dtype)


Shape: (2, 3)
Size: 6
Data Type: int64


# Array Creation Techniques
Objective: Explore different ways to create arrays in NumPy.

In [ ]:
# Create an array filled with zeros
zeros = np.zeros((2, 3))
print("Zeros:\n", zeros)

# Create an array filled with ones
ones = np.ones((3, 2))
print("\nOnes:\n", ones)

# Create an array with a range of elements
range_array = np.arange(10)
print("\nRange Array:", range_array)


Zeros:
 [[0. 0. 0.]
 [0. 0. 0.]]

Ones:
 [[1. 1.]
 [1. 1.]
 [1. 1.]]

Range Array: [0 1 2 3 4 5 6 7 8 9]


Reshaping and Flattening Arrays

Objective: Modify the shape of arrays without changing their data.

In [ ]:
# Reshape arr_2d to 3x2
reshaped = arr_2d.reshape((3, 2))
print("Reshaped to 3x2:\n", reshaped)

# Flatten arr_2d to a 1D array
flattened = arr_2d.flatten()
print("\nFlattened Array:", flattened)


Reshaped to 3x2:
 [[1 2]
 [3 4]
 [5 6]]

Flattened Array: [1 2 3 4 5 6]


Concatenating and Splitting Arrays

Objective: Learn to combine and divide arrays.

In [ ]:
# Concatenate arr_1d and a new array
arr_3 = np.array([6, 7, 8, 9, 10])
concatenated = np.concatenate([arr_1d, arr_3])
print("Concatenated Array:", concatenated)

# Split concatenated array into three parts
split = np.split(concatenated, [5, 8])
print("\nSplit Array:", split)


Concatenated Array: [ 1  2  3  4  5  6  7  8  9 10]

Split Array: [array([1, 2, 3, 4, 5]), array([6, 7, 8]), array([ 9, 10])]


# Linear Algebra and Statistical Operations

Matrix Operations

Objective: Perform basic linear algebra operations.

In [ ]:
# Matrix multiplication
A = np.array([[1, 2], [3, 4]])
B = np.array([[5, 6], [7, 8]])
product = np.dot(A, B)
print("Matrix Product:\n", product)

# Find the determinant of A
det_A = np.linalg.det(A)
print("\nDeterminant of A:", det_A)


Matrix Product:
 [[19 22]
 [43 50]]

Determinant of A: -2.0000000000000004


Statistical Analysis

Objective: Apply statistical methods to analyze data.

In [ ]:
# Calculate mean, median, and standard deviation
data = np.array([1, 2, 3, 4, 5, 6, 7, 8, 9, 10])
print("Mean:", np.mean(data))
print("Median:", np.median(data))
print("Standard Deviation:", np.std(data))

# Find unique elements and their counts
unique_elements, counts = np.unique(data, return_counts=True)
print("\nUnique Elements:", unique_elements)
print("Counts:", counts)


Mean: 5.5
Median: 5.5
Standard Deviation: 2.8722813232690143

Unique Elements: [ 1  2  3  4  5  6  7  8  9 10]
Counts: [1 1 1 1 1 1 1 1 1 1]
