In [ ]:
!pip install numpy

# Basics of NumPy Arrays

In [ ]:
import numpy as np

## Create NumPy arrays and inspect their attributes.

Creating Arrays

In [ ]:
# Create a 1D array from a list
arr_1d = np.array([1, 2, 3, 4, 5])
print("1D Array:", arr_1d)

# Create a 2D array from a nested list
arr_2d = np.array([[1, 2, 3],
                   [4, 5, 6]])
print("\n2D Array:\n", arr_2d)


1D Array: [1 2 3 4 5]

2D Array:
 [[1 2 3]
 [4 5 6]]


Inspecting Array Attributes

In [ ]:
# Print the shape, size, and data type of arr_2d
print("Shape:", arr_2d.shape)
print("Size:", arr_2d.size)
print("Data Type:", arr_2d.dtype)


Shape: (2, 3)
Size: 6
Data Type: int64


# Array Creation Techniques
Objective: Explore different ways to create arrays in NumPy.

In [ ]:
# Create an array filled with zeros
zeros = np.zeros((2, 3))
print("Zeros:\n", zeros)

# Create an array filled with ones
ones = np.ones((3, 2))
print("\nOnes:\n", ones)

# Create an array with a range of elements
range_array = np.arange(10)
print("\nRange Array:", range_array)


Zeros:
 [[0. 0. 0.]
 [0. 0. 0.]]

Ones:
 [[1. 1.]
 [1. 1.]
 [1. 1.]]

Range Array: [0 1 2 3 4 5 6 7 8 9]


## Reshaping and Flattening Arrays

Objective: Modify the shape of arrays without changing their data.

In [ ]:
# Reshape arr_2d to 3x2
reshaped = arr_2d.reshape((3, 2))
print("Reshaped to 3x2:\n", reshaped)

# Flatten arr_2d to a 1D array
flattened = arr_2d.flatten()
print("\nFlattened Array:", flattened)


Reshaped to 3x2:
 [[1 2]
 [3 4]
 [5 6]]

Flattened Array: [1 2 3 4 5 6]


## Concatenating and Splitting Arrays

Objective: Learn to combine and divide arrays.

In [ ]:
# Concatenate arr_1d and a new array
arr_3 = np.array([6, 7, 8, 9, 10])
concatenated = np.concatenate([arr_1d, arr_3])
print("Concatenated Array:", concatenated)

# Split concatenated array into three parts
split = np.split(concatenated, [5, 8])
print("\nSplit Array:", split)


Concatenated Array: [ 1  2  3  4  5  6  7  8  9 10]

Split Array: [array([1, 2, 3, 4, 5]), array([6, 7, 8]), array([ 9, 10])]


# Linear Algebra and Statistical Operations

## Matrix Operations

Objective: Perform basic linear algebra operations.

In [ ]:
# Matrix multiplication
A = np.array([[1, 2], [3, 4]])
B = np.array([[5, 6], [7, 8]])
product = np.dot(A, B)
print("Matrix Product:\n", product)

# Find the determinant of A
det_A = np.linalg.det(A)
print("\nDeterminant of A:", det_A)


Matrix Product:
 [[19 22]
 [43 50]]

Determinant of A: -2.0000000000000004


## Statistical Analysis

Objective: Apply statistical methods to analyze data.

In [ ]:
# Calculate mean, median, and standard deviation
data = np.array([1, 2, 3, 4, 4, 5, 6, 7, 8, 9, 10])
print("Mean:", np.mean(data))
print("Median:", np.median(data))
print("Standard Deviation:", np.std(data))

# Find unique elements and their counts
unique_elements, counts = np.unique(data, return_counts=True)
print("\nUnique Elements:", unique_elements)
print("Counts:", counts)


Mean: 5.363636363636363
Median: 5.0
Standard Deviation: 2.7723546694503467

Unique Elements: [ 1  2  3  4  5  6  7  8  9 10]
Counts: [1 1 1 2 1 1 1 1 1 1]


## Uniform Distribution

The uniform distribution is perhaps the simplest type of distribution, representing an equal probability of all values in a specified range.

In [ ]:
import numpy as np

# Generate 10 random numbers from a uniform distribution between 0 and 1
uniform_data = np.random.rand(10)

# Generate 10 random numbers from a uniform distribution between 10 and 20
uniform_data_scaled = np.random.uniform(10, 20, 10)

print("Uniform distribution [0, 1):")
print(uniform_data)
print("\nUniform distribution [10, 20):")
print(uniform_data_scaled)


Uniform distribution [0, 1):
[0.88786461 0.17253161 0.59185782 0.45923683 0.29506678 0.12091534
 0.78130072 0.86229891 0.55054714 0.53291416]

Uniform distribution [10, 20):
[18.39160865 11.75813954 13.78375639 16.87141899 19.79160687 13.34972703
 11.06234439 17.10452877 11.91117082 11.4258339 ]


## Normal (Gaussian) Distribution

The normal distribution is a common continuous probability distribution, often used in the natural and social sciences to represent real-valued random variables whose distributions are not known.

In [ ]:
# Generate 10 random numbers from a normal distribution with mean=0 and std=1
normal_data = np.random.randn(10)

# Generate 10 random numbers from a normal distribution with mean=50 and std=10
normal_data_scaled = np.random.normal(50, 10, 10)

print("Standard normal distribution (mean=0, std=1):")
print(normal_data)
print("\nNormal distribution (mean=50, std=10):")
print(normal_data_scaled)


Standard normal distribution (mean=0, std=1):
[-0.02482656 -0.64325989  0.06757503 -0.28233546  0.25361988  1.05651917
  0.29388544  0.16363496 -1.54330896  0.22661058]

Normal distribution (mean=50, std=10):
[56.64931756 55.83339035 57.47466779 51.84996898 35.84426471 38.06161215
 49.50153814 47.77231215 42.08710584 43.40909444]


## Binomial Distribution

The binomial distribution represents the number of successes in a sequence of independent experiments.

In [ ]:
# Generate 10 random numbers from a binomial distribution with n=10 and p=0.5
binomial_data = np.random.binomial(n=10, p=0.5, size=10)

print("Binomial distribution (n=10, p=0.5):")
print(binomial_data)


Binomial distribution (n=10, p=0.5):
[5 6 4 4 8 5 3 6 6 5]


## Poisson Distribution
The Poisson distribution is a discrete distribution that expresses the probability of a given number of events occurring in a fixed interval of time or space.

In [ ]:
# Generate 10 random numbers from a Poisson distribution with lambda=3
poisson_data = np.random.poisson(lam=3, size=10)

print("Poisson distribution (lambda=3):")
print(poisson_data)


Poisson distribution (lambda=3):
[5 6 4 1 2 8 0 3 1 3]


## Customizing Random Number Generation
NumPy's random module also supports seeding the random number generator, which can be useful for creating reproducible results during testing or analysis.

In [ ]:
# Seed the random number generator for reproducibility
np.random.seed(85)

# Now, generate random numbers as before
uniform_data_seeded = np.random.rand(5)
print("Uniform distribution with seed (42):")
print(uniform_data_seeded)


Uniform distribution with seed (42):
[0.62037381 0.50895307 0.29824484 0.65379871 0.27350653]
